In [ ]:
# numpy


In [ ]:
!pip install numpy

In [ ]:
# importing numpy library
import numpy as np

In [ ]:
# create an array
arr = np.array([1,2,3])
arr

In [ ]:
type(arr) # data type

In [ ]:
# to get dimension 
arr.shape

In [ ]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b

In [ ]:
b.shape

In [ ]:
type(b)

In [ ]:
b.dtype #data type of element

In [ ]:
np.zeros_like(b)

In [ ]:
np.zeros(1)     # flot values 

In [ ]:
np.zeros((2,3),dtype=np.int32)  # convert into integer

In [ ]:
np.ones_like(b,dtype=np.int32)

In [ ]:
np.full((4,5),5,dtype=np.int32) #create a 2D array 

In [ ]:
np.eye(4,dtype=np.int32) #to craete the identity matrix


In [ ]:
np.diag([1,2,3])

In [ ]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])

b > 7  # to check the elements greater than 7

In [ ]:
b[b>7] # to get the elements greater than  7

# np.arange(start,stop,step)

In [ ]:
import numpy as np

In [ ]:
np.arange(4)

In [ ]:
np.arange(4,10)

In [ ]:
np.arange(4,20,2)

In [ ]:
np.arange(10,4,-1)

# Accessing and Slicing Numpy array elements¶

In [ ]:
a = np.arange(4,10)
a

In [ ]:
a[3]

In [ ]:
print(a[0,3]) # to access multiple elements 
print(a[[0,3]])

In [ ]:
try:
    print(a[0,3]) # to access multiple elements 
except:
    print(a[[0,3]])

In [ ]:
a = np.array([[ 0,  1,  2,  3],[ 4,  5,  6,  7],[ 8,  9, 10, 11],[12, 13, 14, 15]])
a

In [ ]:
# a[rowIndex,columnIndex]
# to excess 14
a[3,2]

In [ ]:
# to get 6,7,10,11
a[1:3,2:]

In [ ]:
# similarly to get 1,2,5,6
a[0:2,1:3]

# Matrix operations
    

In [ ]:
import numpy as np

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2,3],[4,5,6]])

In [ ]:
a*b # it give dot wise multiplication which is not a matrix multiplication


In [ ]:
a + b

In [ ]:
a.dot(b)   # this is matrix multiplication method in numpy as you can see it gives us error
# Multiplication of two matrices a and b is defined only if the number of columns in a is equal to the number of rows b

In [ ]:
a- b

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
a.dot(b)

In [ ]:
type(a)

In [ ]:
a.shape

In [ ]:
b.shape

In [ ]:
a + b

In [ ]:
a - b

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2,3],[4,5,6]])

In [ ]:
a + b

In [ ]:
a - b

# random no 
* A random number is a number chosen as if by chance from some specified distribution such that selection of a large set of these numbers reproduces the underlying distribution. Almost always, such numbers are also required to be independent, so that there are no correlations between successive numbers.

* np.random.random()
* generates a random number from 0 to 1

In [ ]:
np.random .random()

In [ ]:
print(np.random .random())
print(np.random.random())


In [ ]:
print(np.random .random())
print(np.random.random())
print(np.random .random())
print(np.random.random())

In [ ]:
# The np.random.seed() function sets the starting number used to generate a sequence of random numbers 
# it ensures that you get the same result if you start with that same seed each time you run the same process

In [ ]:
np.random.seed(200)
print(np.random.random())
print(np.random.random())

In [ ]:
np.random.seed(200)
print(np.random.random())
print(np.random.random())

In [ ]:
x = np.random.random((2, 3))
x

# np.random.randint()

In [ ]:
# to choose distinct random no


In [ ]:
a = np.random.randint(low = 0, high =10)  # high parameter is exclusive

a

In [ ]:
np.random.seed(100)
a = np.random.randint(low = 0, high =10, size= 100)
a

In [ ]:
np.random.seed(100)
a = np.random.randint(low = 0, high =10, size=100)
a

In [ ]:
Presentation 


In [1]:
import numpy as np

# np.round()
rounds an array to given number of decimals

In [3]:
x = np.random.random((2,3))
print(x)

[[0.60787666 0.28031244 0.50004991]
 [0.67252812 0.39248705 0.20807937]]


In [4]:
np.round(x,2)

array([[0.61, 0.28, 0.5 ],
       [0.67, 0.39, 0.21]])

# astype()
to change the data type of elements

In [5]:
x.astype(int)

array([[0, 0, 0],
       [0, 0, 0]])

In [6]:
x.astype(float)

array([[0.60787666, 0.28031244, 0.50004991],
       [0.67252812, 0.39248705, 0.20807937]])

# reshape()
to reshape an array.

In [7]:
a = np.arange(0,21)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [8]:
a.reshape((4,4))

ValueError: cannot reshape array of size 21 into shape (4,4)

In [9]:
a.reshape((3,7))

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20]])

In [10]:
a.reshape(-1) # to convert ndarray into 1d array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

# Some Other Mathematical operations on np arrays

In [11]:
x = np.array([0,30,45,60,90])

In [12]:
np.sin(x)


array([ 0.        , -0.98803162,  0.85090352, -0.30481062,  0.89399666])

In [13]:
np.cos(x)

array([ 1.        ,  0.15425145,  0.52532199, -0.95241298, -0.44807362])

# np.sum()
to get the sum of all the elements

In [14]:
np.sum(x)

225

In [15]:
a = np.array([[1,2,3],[2,3,4],[1,5,9]])
print(a)

[[1 2 3]
 [2 3 4]
 [1 5 9]]


In [18]:
np.sum(a,axis=1) #for row

array([ 6,  9, 15])

In [17]:
np.sum(a,axis=0) #for col

array([ 4, 10, 16])

In [19]:
np.sum([[0, 1], [0, 5]], axis=0)

array([0, 6])

In [20]:
np.sum([[0, 1], [0, 5]], axis=1)

array([1, 5])

In [22]:
a = np.array([[[1,2,3],[2,3,4],[1,5,9]]])
print(a)

[[[1 2 3]
  [2 3 4]
  [1 5 9]]]


In [23]:
np.sum(a,axis=0)

array([[1, 2, 3],
       [2, 3, 4],
       [1, 5, 9]])