In [1]:
import numpy as np

In [2]:
a =np.array([[2,3],[3,4],[4,5]])
a

array([[2, 3],
       [3, 4],
       [4, 5]])

In [3]:
type(a)

numpy.ndarray

In [5]:
a.shape

(3, 2)

In [6]:
a.dtype

dtype('int32')

In [7]:
np.zeros_like(a)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [10]:
np.arange(3)

array([0, 1, 2])

In [19]:
np.arange(1,21)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [13]:
np.arange(21,0,-1)

array([21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,
        4,  3,  2,  1])

In [15]:
a = np.array([[2,3],[4,5],[6,7]])
a

array([[2, 3],
       [4, 5],
       [6, 7]])

In [16]:
type(a)

numpy.ndarray

In [17]:
a.shape

(3, 2)

In [23]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
np.zeros((2,3),dtype=np.int32)

array([[0, 0, 0],
       [0, 0, 0]])

In [28]:
np.ones((2,3),dtype=np.int32)

array([[1, 1, 1],
       [1, 1, 1]])

In [29]:
np.zeros_like(a,dtype=np.int32)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [30]:
np.ones_like(a,dtype=np.int32)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [31]:
np.full((4,5),3,dtype=np.int32)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [34]:
np.eye(2,dtype=np.int32)

array([[1, 0],
       [0, 1]])

In [41]:
a = np.diag((1,2,3))
print(a)
print(a.dtype)

[[1 0 0]
 [0 2 0]
 [0 0 3]]
int32


In [37]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [43]:

a = np.array([2,4,6,8,10,12,14,16])
a


array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [44]:
a[0]

2

In [45]:
a[-2]

14

In [48]:
a[[0,4,6]]

array([ 2, 10, 14])

In [49]:
a = np.array([[ 0,  1,  2,  3],[ 4,  5,  6,  7],[ 8,  9, 10, 11],[12, 13, 14, 15]])
print(a)
print(a[1,2])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
6


In [50]:
a>5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [69]:
a[0:4:3,1:4:2]

array([[ 1,  3],
       [13, 15]])

In [70]:
np.random.random()

0.7320191887004689

In [76]:
np.random.seed(100)
print(np.random.random());print(np.random.random())


0.5434049417909654
0.27836938509379616


In [79]:
np.random.seed(100)
print(np.random.random());print(np.random.random())

0.5434049417909654
0.27836938509379616


In [82]:
x = np.random.random((3,4))
x

array([[0.21969749, 0.97862378, 0.81168315, 0.17194101],
       [0.81622475, 0.27407375, 0.43170418, 0.94002982],
       [0.81764938, 0.33611195, 0.17541045, 0.37283205]])

In [84]:
s = np.random.randint(low=2,high=100,size=4)
s

array([65, 55, 29, 58])

In [86]:
a = [75,65,69,21,7,30,90,4,45,16]


In [88]:
np.random.seed(100)
np.random.choice(a,size = (3,5))

array([[45, 45, 21,  4,  4],
       [75,  7, 69, 30, 69],
       [69, 69, 65, 75, 45]])